### ISSUE TITLE
Is import async?

### ISSUE THREAD

**Issue by trusktr** [ModuleLoader/es6-module-loader#280]
Is `import` at the top of an ES6 module file loaded asynchronously?

**Comment by guybedford** [comment]
No imports are static, the code is only executed when its dependencies are ready.

**Comment by trusktr** [comment]
Is this because of following the ES6 spec, not because of implementation technicalities?

**Comment by guybedford** [comment]
Both. If `import` was just an asynchronous function, then it would no longer be possible to statically analyze modules, as just like CommonJS require, I could have import within arbitrary conditions etc. At a specified level, that does not define a "complete" system from a perspective of static analysis. That is, browserify doesn't work perfectly for all possible code variations due to the dynamic nature of a `require` function. Also, ES6 gives shared bindings of circular references, which is not possible with a dynamic import function. It's interesting to run through the variations of systems that may have been possible. I tend to think ES6 modules make a lot of sense.

**Comment by trusktr** [comment]
What specifically would static analyses be used for?

**Comment by guybedford** [comment]
Bundling.

**Comment by trusktr** [comment]
Can you just scan a whole file and see require/import statements anywhere in the file, and just bundle all modules, even if the flow of code doesn't ultimately load them at runtime?

**Comment by guybedford** [comment]
ES6 flow does load them all at runtime unlike CommonJS.

**Comment by trusktr** [comment]
Well, in that case, can't

```js
var blah = function() {
  import something from 'something'
}
if (isSomething()) blah()
```

work?

**Comment by guybedford** [comment]
`import` only works at the base level. They are static and always load before the module is run.

**Comment by trusktr** [comment]
I know, I get that part, but what I mean is what's stopping you (generally speaking, anyone working on ES6 Module spec) from scanning the whole file, and loading what's anywhere in the file before running the file?

**Comment by guybedford** [comment]
@trustkr it's good to be interested in these mechanics, I'm not sure I understand your question though - this isn't really the best place for long discussions about specific specification decisions. Perhaps we can continue the discussion on chat.

**Comment by trusktr** [comment]
Which channel? es6-module-loader doesn't seem to exist.
