### ISSUE TITLE
add ability to enable jsx support for babe

### ISSUE THREAD

**Issue by johlrich** [ModuleLoader/es6-module-loader#311]
Would there be a way to revert or modify the strategy for disabling jsx support? With the current strategy I cannot manually enable it by passing in an empty blacklist array.

Perhaps something like having `options.blacklist || ['react']` may satisfy a desire to have jsx off by default and still allow it to be enabled. Thoughts?

**Comment by guybedford** [comment]
Have you tried passing `'react` in the whitelist?

**Comment by johlrich** [comment]
I had not when I posted, but just tried and this did not work. Babel checks the blacklist first and returns false immediately when deciding of a transformer can run.

**Comment by guybedford** [comment]
Ok sure. I'm not sure we want to make JSX possible through this route. We should stick to that which is definitely within the future extension possibilities of JavaScript itself. Rather add a custom `transform` hook to the loader that uses 6to5 to do special transformations if you need?

**Comment by johlrich** [comment]
Hm, why not allow JSX (or more generally any particular transformation) through the transpiler? If a transpiler allow us to both bring spec complete upcoming features as well as iterate on the potential future today, then I think this module loader polyfill already enabled both stories without the blackisted transformer (as long as the transpiler always generates valid ES6 modules with valid JS inside).

**Comment by guybedford** [comment]
Because we should treat all custom compilation equally and not give arbitrary preference to some. The way to implement compile-to-js is through the translate hook. The included transformation is all about bringing us to ES6 modules, nothing more, and the transform will be deprecated when ES6 modules have full native support.

**Comment by johlrich** [comment]
Ah, that does make more sense. I was getting caught up in "the tool I want to use is there already mentality" versus the spec'd way of handling translation. Closing, thanks.

**Comment by hipertracker** [comment]
That permanent blocking react is not consistent and not wise. 

First, why only 'react' is blacklisted but not  'flow', 'experimental', 'playground' or  'loose' mode? 

Second, 'es6-module-loader' is used not only for ES6 modules but as a part of other projects, like excelent [jspm](http://jspm.io/) package manager. Because of that blacklisted option I cannot use JSX in React projects. :(

And last, but not least, why the heck not allow to overwrite that blacklist? Because it is the last statement in the code it cannot be changed. It looks like a bug, not a feature.
