### ISSUE TITLE
ES6 module loader should correctly handle duplicate entries in dependency list

### ISSUE THREAD

**Issue by vladima** [ModuleLoader/es6-module-loader#363]
We are working on adding TypeScript to the list of supported transpilers in ES6 module loader. One aspect that is looks unspecified and inconsistent is how ES6 module loader handles duplicate entries in dependency list. Consider this:
```ts
export {x} from 'b';
export {y} from 'b';
```
TypeScript will transpile it to 
```javascript
System.register(['b', 'b'], function(exports_1) {
    return {
        setters:[
            function (_b_1) {
                exports_1("x", _b_1["x"]);
            },
            function (_b_2) {
                exports_1("y", _b_2["y"]);
            }],
        execute: function() {
        }
    }
});
```
In the converted code for every import/export statement TypeScript compiler produces a separate dependency entry and setter. When module is instantiated ES6 module loader will call both setters however if something in module 'b' calls exporter function - only first setter will be invoked. 
Relevant bits of the source code are [here](https://github.com/ModuleLoader/es6-module-loader/blob/master/src/loader.js#L728).

The fix seem to be fairly simple - I can submit it as a part of my work for adding TypeScript support to the  ES6 module loader.

Related TypeScript bug: https://github.com/Microsoft/TypeScript/issues/2943

**Comment by guybedford** [comment]
@vladima it's amazing to see this being implemented in TypeScript - really nice work. I'd suggest having the dependencies deduped by default in the output. Although if you think keeping duplicates and making that work in the implementation is better I'm happy to consider it.

**Comment by cmichaelgraham** [comment]
i have a port of the @EisenbergEffect [aurelia repos](https://github.com/aurelia/) to [typescript](https://github.com/cmichaelgraham/aurelia-ts-port).  

using [gulp-typescript](https://github.com/ivogabe/gulp-typescript) from @ivogabe, i can [gulp build](https://github.com/cmichaelgraham/aurelia-ts-port/blob/master/aurelia-ts/gulpfile.js#L140-L180) 
* [amd](https://github.com/cmichaelgraham/aurelia-ts-port/tree/master/dist/amd), 
* [commonjs](https://github.com/cmichaelgraham/aurelia-ts-port/tree/master/dist/commonjs), 
* [es6](https://github.com/cmichaelgraham/aurelia-ts-port/tree/master/dist/es6), and 
* [system.register](https://github.com/cmichaelgraham/aurelia-ts-port/tree/master/dist/system) distributions.  

the issue described here is very important to me because the generated system.register has the above (not deduped dependencies), as you can see [here](https://github.com/cmichaelgraham/aurelia-ts-port/blob/master/dist/system/dependency-injection/index.js#L1)

has there been any discussion with @mhegazy and @jonathandturner about the plan to resolve this?

**Comment by vladima** [comment]
It was discussed and the fix is included in [this PR](https://github.com/ModuleLoader/es6-module-loader/pull/366)

**Comment by cmichaelgraham** [comment]
thank you!  you folks are amazing :+1:
