### ISSUE TITLE
Incompatible with Babel 6.0.0

### ISSUE THREAD

**Issue by Alhadis** [ModuleLoader/es6-module-loader#445]
Babel 6 was released recently, which introduced a number of [very breaking changes](http://babeljs.io/blog/2015/10/29/6.0.0/) to the API. Specifically, the NodeJS API has moved from `babel` to [`babel-core`](https://www.npmjs.com/package/babel-core).

This has broken the ES6 Module Loader.

**Comment by drewlustro** [comment]
+1 it's quite busted with browserify too (and consequently my `babelify` setup).

The `when` dependency tries to include `./makePromises`, which doesn't resolve because the `require` has already been replaced.

`Error: Cannot find module './makePromise' from '/Users/drew/dev-local/glsl-park/node_modules/es6-module-loader/node_modules/when/es6-shim'`

**Comment by hbrysiewicz** [comment]
+1

**Comment by guybedford** [comment]
With Babel 6, transpilation workflows will move to be always plugin-based. This support is being tracked at https://github.com/systemjs/systemjs/issues/953.

**Comment by guybedford** [comment]
Tracking in https://github.com/ModuleLoader/es6-module-loader/issues/463.
